#!/usr/bin/perl
use App::Fasops;

App::Fasops->run;

=head1 OVERVIEW

For help with App::Fasops, run "fasops help"

=cut

__END__

perl -I lib/ bin/fasops

perl -I lib/ bin/fasops names t/example.fas -c -o stdout

perl -I lib/ bin/fasops subset t/example.fas t/example.name.list -o stdout

perl -I lib/ t/04-subset.t
