#!/usr/bin/perl
use App::Fasops;

App::Fasops->run;

=head1 OVERVIEW

For help with App::Fasops, run "fasops help"

=cut

__END__

perl -I lib/ script/fasops

perl -I lib/ script/fasops names t/example.fas -c -o stdout

perl -I lib/ script/fasops subset t/example.fas t/example.name.list -o stdout

perl -I lib/ t/04-subset.t

perl -I lib/ script/fasops separate t/example.fas --nodash --rc
perl -I lib/ script/fasops separate t/example.fas --nodash --rc -o stdout

perl -I lib/ script/fasops covers t/example.fas -o stdout -n S288c

perl -I lib/ script/fasops axt2fas t/example.axt -o stdout
perl -I lib/ script/fasops maf2fas t/example.maf -o stdout
