name: Docker

on:
  push:
    paths:
      - .github/workflows/docker.yml
      - Dockerfile
    tags:
      - '*'

env:
  IMAGE_NAME: wangq/fasops

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build Docker image
        run: docker build -t "${{ env.IMAGE_NAME }}" .

      - name: Run fasops help
        run: docker run --rm "${{ env.IMAGE_NAME }}" fasops help

      - name: Login to Docker Hub
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKERHUB_USER: ${{ secrets.DOCKER_USER }}
        run: echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USER --password-stdin
